### ISSUE TITLE
not build ffmpeg-invoke.cpp file 

### ISSUE THREAD

**Issue by mansiJspaceo** [AnJoiner/FFmpegCommand#5]
while build ffmpeg-invoke.cpp file got this error 

**/ffmpeg/libavutil/x86/timer.h:39:23: error: invalid
      output constraint '=a' in asm
                     :"=a" (a), "=d" (d));**

also another error is

**libavcodec/x86/mathops.h:118:12: error: invalid
      input constraint 'ic' in asm
         : "ic" ((uint8_t)(-s))**

another is

**ffmpeg/libavcodec/x86/mathops.h:127:12: error: invalid
      input constraint 'ic' in asm
         : "ic" ((uint8_t)(-s))**

how to solve this error build ffmpeg-invoke.cpp success full

**Comment by AnJoiner** [comment]
Sorry,  Could you tell me which way do you compile, ndk-build or CMake？And you can describe your configuration of ffmpeg build  in detail .

**Comment by mansiJspaceo** [comment]
yeah sure..

for build ffmpeg-invoke.so file follow this artical 
**https://juejin.im/post/5d440504f265da03b6388ed2**

ffmpeg version:- 4.2.2
ndk Version:- NDK-r19c

only problem in build **ffmpeg-invoke.so** file

Thank you in Adavance

**Comment by AnJoiner** [comment]
Please tell me your operating system, Windows or Linux. And other dependent software, I will try it.

**Comment by AnJoiner** [comment]
I compile without problems, you can refer to this document[FFmpeg4.2.2-Build](https://github.com/AnJoiner/FFmpegCommand/blob/master/FFmpeg4.2.2-Build.md)

**Comment by mansiJspaceo** [comment]
Thank you so much

**Comment by mansiJspaceo** [comment]
i build with this ..but there are only generate with armani-7a .. when i
built arm64-8a it's give a error... not build ffmpeg-invoke.so file.

Any idea for this how can we build for this

**Comment by AnJoiner** [comment]
In fact compiling armeabi-v7a is enough, but using the latest version of ndk to compile arm64-v8a will give an error. I used ndk-14b to compile successfully, you can try it.

**Comment by mansiJspaceo** [comment]
Thank you so much

**Comment by mansiJspaceo** [comment]
when i build with ndk-r19c & ffmpeg 4.2.2 it build successfull with x86 & x86_64 ... but can not build with arm7a or arm64-8a how can i solve this.

error same:-

**/ffmpeg/libavutil/x86/timer.h:39:23: error: invalid
output constraint '=a' in asm
:"=a" (a), "=d" (d));

also another error is

libavcodec/x86/mathops.h:118:12: error: invalid
input constraint 'ic' in asm
: "ic" ((uint8_t)(-s))

another is

ffmpeg/libavcodec/x86/mathops.h:127:12: error: invalid
input constraint 'ic' in asm
: "ic" ((uint8_t)(-s))**


i want to build with latest ndk & lastest ffmpeg version.
