### ISSUE TITLE
when i build with ndk-r19c & ffmpeg 4.2.2 it build successfull with x86 & x86_64 ... but can not build with arm7a or arm64-8a how can i solve this.

### ISSUE THREAD

**Issue by mansiJspaceo** [AnJoiner/FFmpegCommand#9]
when i build with ndk-r19c & ffmpeg 4.2.2 it build successfull with x86 & x86_64 ... but can not build with arm7a or arm64-8a how can i solve this.

error same:-

**/ffmpeg/libavutil/x86/timer.h:39:23: error: invalid
output constraint '=a' in asm
:"=a" (a), "=d" (d));

also another error is

libavcodec/x86/mathops.h:118:12: error: invalid
input constraint 'ic' in asm
: "ic" ((uint8_t)(-s))

another is

ffmpeg/libavcodec/x86/mathops.h:127:12: error: invalid
input constraint 'ic' in asm
: "ic" ((uint8_t)(-s))**

i want to build with latest ndk & lastest ffmpeg version.

_Originally posted by @mansiJspaceo in https://github.com/AnJoiner/FFmpegCommand/issues/5#issuecomment-580078057_
